import { Product, Category } from './types';

export const categories: Category[] = [
  { id: 'all', name: 'All Products', slug: 'all' },
  { id: 'fruits', name: 'Fruits', slug: 'fruits' },
  { id: 'vegetables', name: 'Vegetables', slug: 'vegetables' },
  { id: 'dairy', name: 'Dairy', slug: 'dairy' },
  { id: 'meat', name: 'Meat & Seafood', slug: 'meat' },
  { id: 'bakery', name: 'Bakery', slug: 'bakery' },
  { id: 'beverages', name: 'Beverages', slug: 'beverages' },
];

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Fresh Organic Bananas',
    price: 2.99,
    image: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=300&h=300&fit=crop',
    category: 'fruits',
    description: 'Sweet, ripe organic bananas perfect for smoothies or snacking.',
    inStock: true,
    rating: 4.5,
  },
  {
    id: '2',
    name: 'Greek Yogurt',
    price: 5.99,
    image: 'https://images.unsplash.com/photo-1571212515416-fbb88c3704ac?w=300&h=300&fit=crop',
    category: 'dairy',
    description: 'Creamy Greek yogurt packed with protein and probiotics.',
    inStock: true,
    rating: 4.8,
  },
  {
    id: '3',
    name: 'Organic Spinach',
    price: 3.49,
    image: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=300&h=300&fit=crop',
    category: 'vegetables',
    description: 'Fresh organic baby spinach leaves, perfect for salads.',
    inStock: true,
    rating: 4.3,
  },
  {
    id: '4',
    name: 'Artisan Sourdough Bread',
    price: 4.99,
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=300&h=300&fit=crop',
    category: 'bakery',
    description: 'Handcrafted sourdough bread with a crispy crust.',
    inStock: false,
    rating: 4.7,
  },
  {
    id: '5',
    name: 'Fresh Atlantic Salmon',
    price: 12.99,
    image: 'https://images.unsplash.com/photo-1499125562588-29fb8a56b4d1?w=300&h=300&fit=crop',
    category: 'meat',
    description: 'Premium Atlantic salmon fillet, sustainably sourced.',
    inStock: true,
    rating: 4.6,
  },
  {
    id: '6',
    name: 'Organic Apple Juice',
    price: 3.99,
    image: 'https://images.unsplash.com/photo-1544145945-f90425340c7e?w=300&h=300&fit=crop',
    category: 'beverages',
    description: 'Pure organic apple juice, no added sugars.',
    inStock: true,
    rating: 4.2,
  },
  {
    id: '7',
    name: 'Red Bell Peppers',
    price: 4.49,
    image: 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=300&h=300&fit=crop',
    category: 'vegetables',
    description: 'Crisp and sweet red bell peppers, locally grown.',
    inStock: true,
    rating: 4.4,
  },
  {
    id: '8',
    name: 'Organic Strawberries',
    price: 6.99,
    image: 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=300&h=300&fit=crop',
    category: 'fruits',
    description: 'Juicy organic strawberries, perfect for desserts.',
    inStock: true,
    rating: 4.9,
  },
];